




SELECT DATE ( AL1.TIMESTAMP ) AS TRANSACTION_DATE 
	, LOWER ( AL5.PAGE_VIEW_ATTRIBUTE22 ) AS REP_NAME 
	, CASE WHEN LOWER(SUBSTR(AL2.ELEMENT_ATTRIBUTE15, 1, 2)) = 'm.' THEN 'www.' || LOWER(SUBSTR(AL2.ELEMENT_ATTRIBUTE15, 3)) ELSE LOWER(AL2.ELEMENT_ATTRIBUTE15) END AS PAGE_NAME 
	, CASE WHEN NOT AL7.ELEMENT_ATTRIBUTE2 = 'N/A' THEN AL7.ELEMENT_ATTRIBUTE2 WHEN NOT  AL4.SECOND_LEVEL_DOMAIN = '' THEN AL4.SECOND_LEVEL_DOMAIN ELSE '(Unknown)' END AS ORGANISATION_NAME
	, CASE WHEN SUBSTR(LOWER(AL1.ELEMENT_NAME), 1, 7) = 'start|0' THEN LOWER(SUBSTR(AL1.ELEMENT_ATTRIBUTE7, 8)) ELSE LOWER(AL1.ELEMENT_NAME) END AS NC_PAGE_NAME 
	, LOWER(AL1.ELEMENT_CATEGORY) AS NC_TYPE_NAME 
	, CASE WHEN AL3.IS_MOBILE = 'Y' THEN '1' ELSE '0' END AS PLATFORM 
	, AL6.PAGE_VIEW_ATTRIBUTE1 AS IBMER
	, COUNT (DISTINCT AL1.ELEMENT_KEY) AS VIEWS 
	, COUNT (DISTINCT AL1.SESSION_ID) AS VISITS 
	, COUNT (DISTINCT AL1.COOKIE_ID) AS VISITORS 
FROM IBMCOM15.ELEMENT1 AL1 
	LEFT OUTER JOIN IBMCOM15.TECHNICALPROPERTIES1 AL3 ON (AL1.SESSION_ID=AL3.SESSION_ID) 
	LEFT OUTER JOIN IBMCOM15.GEOGRAPHY1 AL4 ON (AL1.SESSION_ID=AL4.SESSION_ID) 
	LEFT OUTER JOIN IBMCOM15.ELEMENT1 AL7 ON (AL1.SESSION_ID=AL7.SESSION_ID) 
	LEFT OUTER JOIN IBMCOM15.ELEMENT2 AL2 ON (AL1.ELEMENT_KEY=AL2.ELEMENT_KEY) 
	LEFT OUTER JOIN IBMCOM15.PAGEVIEW2 AL6 ON (AL2.SESSION_ID=AL6.SESSION_ID AND UPPER(AL2.ELEMENT_ATTRIBUTE15)=AL6.PAGE) 
	LEFT OUTER JOIN IBMCOM15.PAGEVIEW4 AL5 ON (AL6.PAGEVIEW_KEY=AL5.PAGEVIEW_KEY) 
WHERE (AL1.TIMESTAMP BETWEEN DATE('#START_DATE#') AND DATE('#START_DATE#') + 1 
	AND AL1.SITE_ID IN ('INSALES', 'INSREP', 'INSSRV') 
	AND (AL2.ELEMENT_ATTRIBUTE15 LIKE 'm.ibm.com/connect/ibm/%/resources/%' OR AL2.ELEMENT_ATTRIBUTE15 LIKE 'www.ibm.com/connect/ibm/%/resources/%') 
	AND ((AL1.ELEMENT_CATEGORY IN ('DOWNLOAD', 'EXTERNAL LINK', 'PAGE CLICK') AND (NOT AL2.ELEMENT_NAME LIKE 'SKYPE%')) OR (AL1.ELEMENT_CATEGORY='RICH_MEDIA_SERVICE' AND AL1.ELEMENT_NAME LIKE 'START|0 OF%')) 
	AND (AL7.ELEMENT_CATEGORY='COMMON USER TAG' OR AL7.ELEMENT_CATEGORY IS NULL)) 
GROUP BY DATE(AL1.TIMESTAMP)
	, LOWER(AL5.PAGE_VIEW_ATTRIBUTE22)
	, CASE WHEN LOWER(SUBSTR(AL2.ELEMENT_ATTRIBUTE15, 1, 2)) = 'm.' THEN 'www.' || LOWER(SUBSTR(AL2.ELEMENT_ATTRIBUTE15, 3)) ELSE LOWER(AL2.ELEMENT_ATTRIBUTE15) END
	, CASE WHEN NOT AL7.ELEMENT_ATTRIBUTE2 = 'N/A' THEN AL7.ELEMENT_ATTRIBUTE2 WHEN NOT  AL4.SECOND_LEVEL_DOMAIN = '' THEN AL4.SECOND_LEVEL_DOMAIN ELSE '(Unknown)' END
	, CASE WHEN SUBSTR(LOWER(AL1.ELEMENT_NAME ), 1, 7) = 'start|0' THEN LOWER(SUBSTR(AL1.ELEMENT_ATTRIBUTE7, 8)) ELSE LOWER(AL1.ELEMENT_NAME) END
	, LOWER(AL1.ELEMENT_CATEGORY)
	, CASE WHEN AL3.IS_MOBILE = 'Y' THEN '1' ELSE '0' END
	, AL6.PAGE_VIEW_ATTRIBUTE1
	
	SELECT DATE ( AL1.TIMESTAMP ) AS TRANSACTION_DATE
	, LOWER ( AL5.PAGE_VIEW_ATTRIBUTE22 ) AS REP_NAME
	, CASE WHEN LOWER ( SUBSTR ( AL2.ELEMENT_ATTRIBUTE15, 1, 2 ) ) = 'm.' THEN 'www.' || LOWER (  SUBSTR ( AL2.ELEMENT_ATTRIBUTE15, 3 ) ) ELSE LOWER ( AL2.ELEMENT_ATTRIBUTE15 ) END AS PAGE_NAME
	, CASE WHEN NOT AL7.ELEMENT_ATTRIBUTE2 = 'N/A' THEN AL7.ELEMENT_ATTRIBUTE2 WHEN NOT  AL4.SECOND_LEVEL_DOMAIN = '' THEN AL4.SECOND_LEVEL_DOMAIN ELSE '(Unknown)' END ORGANISATION_NAME
	, LOWER ( AL1.ELEMENT_NAME ) AS NC_PAGE_NAME
	, LOWER ( AL1.ELEMENT_CATEGORY ) AS NC_TYPE_NAME
	, CASE WHEN AL3.IS_MOBILE = 'Y' THEN '1' ELSE '0' END AS PLATFORM
	, AL6.PAGE_VIEW_ATTRIBUTE1 AS IBMER
	, COUNT (DISTINCT AL1.ELEMENT_KEY) AS VIEWS
	, COUNT (DISTINCT AL1.SESSION_ID) AS VISITS
	, COUNT (DISTINCT AL1.COOKIE_ID)  AS VISITORS
FROM IBMCOM15.ELEMENT1 AL1 
	LEFT OUTER JOIN IBMCOM15.TECHNICALPROPERTIES1 AL3 ON (AL1.SESSION_ID=AL3.SESSION_ID) 
	LEFT OUTER JOIN IBMCOM15.GEOGRAPHY1 AL4 ON (AL1.SESSION_ID=AL4.SESSION_ID) 
	LEFT OUTER JOIN IBMCOM15.ELEMENT1 AL7 ON (AL1.SESSION_ID=AL7.SESSION_ID) 
	LEFT OUTER JOIN IBMCOM15.ELEMENT2 AL2 ON (AL1.ELEMENT_KEY=AL2.ELEMENT_KEY) 
	LEFT OUTER JOIN IBMCOM15.PAGEVIEW2 AL6 ON (AL2.SESSION_ID=AL6.SESSION_ID AND UPPER ( AL2.ELEMENT_ATTRIBUTE15 )=AL6.PAGE) 
	LEFT OUTER JOIN IBMCOM15.PAGEVIEW4 AL5 ON (AL6.PAGEVIEW_KEY=AL5.PAGEVIEW_KEY) 
WHERE (AL1.TIMESTAMP BETWEEN DATE('#START_DATE#') AND DATE('#START_DATE#') + 1  
	AND AL1.SITE_ID IN ('INSALES', 'INSREP', 'INSSRV') 
	AND (LOWER(AL2.ELEMENT_ATTRIBUTE15) LIKE 'm.ibm.com/connect/ibm/%/resources/%' OR LOWER(AL2.ELEMENT_ATTRIBUTE15) LIKE 'www.ibm.com/connect/ibm/%/resources/%') 
	AND AL1.ELEMENT_CATEGORY IN ('DOWNLOAD', 'EXTERNAL LINK', 'PAGE CLICK') 
	AND (NOT AL2.ELEMENT_NAME LIKE 'SKYPE%') 
	AND (AL7.ELEMENT_CATEGORY='COMMON USER TAG' OR AL7.ELEMENT_CATEGORY IS NULL)) 
GROUP BY DATE ( AL1.TIMESTAMP )
	, LOWER ( AL5.PAGE_VIEW_ATTRIBUTE22 )
	, CASE WHEN LOWER ( SUBSTR ( AL2.ELEMENT_ATTRIBUTE15, 1, 2 ) ) = 'm.' THEN 'www.' || LOWER (  SUBSTR ( AL2.ELEMENT_ATTRIBUTE15, 3 ) ) ELSE LOWER ( AL2.ELEMENT_ATTRIBUTE15 ) END
	, CASE WHEN NOT AL7.ELEMENT_ATTRIBUTE2 = 'N/A' THEN AL7.ELEMENT_ATTRIBUTE2 WHEN NOT  AL4.SECOND_LEVEL_DOMAIN = '' THEN AL4.SECOND_LEVEL_DOMAIN ELSE '(Unknown)' END
	, LOWER ( AL1.ELEMENT_NAME ), LOWER ( AL1.ELEMENT_CATEGORY )
	, CASE WHEN AL3.IS_MOBILE = 'Y' THEN '1' ELSE '0' END
	, AL6.PAGE_VIEW_ATTRIBUTE1